### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by ghost** [msnelling/docker-cloudflared#2]
With Cloudflared, Cloudflare are recommending the use of a config.yml file as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config however after many failed attempts I have not been able to specify the location for the config file I’ve created for use in docker. The locations are that cloudflared looks for are On Unix-like systems, are ~/.cloudflared, /etc/cloudflared and /usr/local/etc/cloudflared in that order. Not sure if it’s something I’m doing wrong? Everything else I’ve configured seems to have worked fine i.e cert location etc. 

Any help, advise would and is appreciated.

**Comment by msnelling** [comment]
Hi @wrwatk, 
Looking at the [docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config#file-location), I think you specify the location of the config file yourself on the command line.
`cloudflared tunnel --config tunnels/config.yml run`

**Comment by msnelling** [comment]
Assuming resolved.
